### ISSUE TITLE
Ошибка вёрстки posts.html

### ISSUE THREAD

**Issue by BogdanRomanko** [okis-okis/scs#10]
1. В файле posts.html весь блок с постом является ссылкой. Надо разделить, чтоб ссылкой на пост было только изображение И название поста, а не вся карточка.
![image](https://github.com/okis-okis/scs/assets/67006710/0ce51f7a-7f26-4e1b-b1e4-15700c6a92c9)

2. Теги под постом в вёрстке тоже нужно обернуть ссылками, чтоб можно было быстро перейти на поиск по тегу
![изображение_2023-11-21_231332369](https://github.com/okis-okis/scs/assets/67006710/647ee807-51e6-4165-bad8-7fe1710ff062)

3. Кнопки "Сначала новые", "Сначала старые" и "Сначала популярные" нужно сделать ссылками, а не через тег `<button>`
![image](https://github.com/okis-okis/scs/assets/67006710/65f71c90-316f-463c-b558-6f0eaf0713e9)

4. Кнопку "Сначала популярные" можно удалить

5. Категории справа нужно обернуть в ссылки, а не просто списком сделать
![image](https://github.com/okis-okis/scs/assets/67006710/e96fbb7a-7a56-44bb-897c-4919fe9e52da)

6. Поле поиска перетянуть лучше или вправо над категориями, или растянуть в полную ширину окна (лучше справа будет смотреться)

7. Автор статьи тоже должен быть обвёрнут ссылкой. Авторов может быть множество

**Comment by zendau** [comment]
Дополню пункт 4. Кнопку "Сначала популярные" стоит удалить.  Так как для её реализации необходимо логика рейтинга который основывается на (пример: лайки, дизлайки, просмотры, кол-во комментариев). У нас только просмотры, для всего остального необходима авторизация. Так что проще пока убрать эту кнопку.
![image](https://github.com/okis-okis/scs/assets/39885938/83ef68a5-ccbe-4d36-8ea1-955c8ad84fbe)

**Comment by okis-okis** [comment]
Спасибо за рекомендации. Ошибки исправил. В следующем обновлении прошу посмотреть и проверить на соответствие требование. В случае, если всё работает, закрой эту тему.
