### ISSUE TITLE
Ошибка вёрстки страницы поста

### ISSUE THREAD

**Issue by BogdanRomanko** [okis-okis/scs#12]
Я просто вставлю две картинки

![image](https://github.com/okis-okis/scs/assets/67006710/aacb092b-a675-4df0-b419-9cd785634fef)

![image](https://github.com/okis-okis/scs/assets/67006710/a5d9f5a3-6ba5-41f5-9869-a472a9b3ac45)

**Comment by zendau** [comment]
Добавлю то что стилей для картинок которые будут в контенте так и нет. Например если схемы вставят верстка может поехать

**Comment by okis-okis** [comment]
Исправил эту ошибку. По поводу стилей самого поста, то я убрал их, чтобы можно было настраивать контент прямо в WordPress.
