### ISSUE TITLE
Вёрстка страницы преподавателей

### ISSUE THREAD

**Issue by BogdanRomanko** [okis-okis/scs#15]
1. Если у преподавателя нет текста описания, то его карточка съезжает

![image](https://github.com/okis-okis/scs/assets/67006710/12fe9740-e6a7-42af-b9e2-f6b4f271a47d)

2. Если у него мало описания, его карточка съезжает

![image](https://github.com/okis-okis/scs/assets/67006710/cc35007f-b019-4c32-82cb-994ad21668a3)

3. Почему-то до сих пор есть стили, чтоб чётные и нечётные преподаватели по-разному отрисовывались

![image](https://github.com/okis-okis/scs/assets/67006710/2ebe4287-7b5c-4bf2-a293-c4ccb92d9491)
![image](https://github.com/okis-okis/scs/assets/67006710/09aff400-434e-4b2a-9fc6-6c21a34e678a)

**Comment by okis-okis** [comment]
Исправлено. Обнови вёрстку
