### ISSUE TITLE
Вёрстка страницы преподавателя

### ISSUE THREAD

**Issue by BogdanRomanko** [okis-okis/scs#16]
Для разных преподавателей по-разному отрисовываются страницы:

![image](https://github.com/okis-okis/scs/assets/67006710/80b6ff00-0d9a-4ed6-b831-ce8786322b7f)

![image](https://github.com/okis-okis/scs/assets/67006710/5451af07-b543-4632-b6fd-ee25952e052b)

**Comment by okis-okis** [comment]
Ширина зафиксирована. Обнови вёрстку в ближайшее время
