### ISSUE TITLE
Фиксированное меню

### ISSUE THREAD

**Issue by zendau** [okis-okis/scs#21]
Фиксированное меню не берет в учет меню вп
![image](https://github.com/okis-okis/scs/assets/39885938/0b3e3cd8-fc8f-4ef9-ad90-aef92cffd11d)

**Comment by okis-okis** [comment]
![изображение_2024-01-09_111010431](https://github.com/okis-okis/scs/assets/67818930/fb2f5221-1f75-41ff-b3f8-348b3802a967)

Ты меню правильно настроил в WP?

**Comment by BogdanRomanko** [comment]
ну у нас кастомное меню, поэтому мы не делали через впшное

**Comment by zendau** [comment]
Меню по шаблону является константой и не может меняться. Если уж сильно хочется поменять есть файлы. Можно добавить и сюда но будет расинхрон с футером поэтому в этом нет смысла. И верстка не поддерживает добавление новых меню 
![image](https://github.com/okis-okis/scs/assets/39885938/2e3dd434-0049-4d23-ad3d-e53a04e0015a)

**Comment by okis-okis** [comment]
Тогда я уберу фиксированное меню, чтобы исправить эту проблему.
