### ISSUE TITLE
Необходимо сделать один шрифт для всего

### ISSUE THREAD

**Issue by zendau** [okis-okis/scs#24]
Есть множество мест где шрифт отличается от используемого. Например страница списка блогов, кнопка "все преподаватели"
![image](https://github.com/okis-okis/scs/assets/39885938/488447d0-aae0-4f94-937c-2440fb8e51cc)
В самом блоге так же отличается 
![image](https://github.com/okis-okis/scs/assets/39885938/19aeb4a0-ea2c-41e8-88a9-295f92a5dbea)

**Comment by okis-okis** [comment]
Исправлено в новой версии вёрстки
