### ISSUE TITLE
Адаптивность на мобильных устройствах

### ISSUE THREAD

**Issue by zendau** [okis-okis/scs#25]
При выборе например в девтулсе galaxy s8+ белая полоса справа 
![image](https://github.com/okis-okis/scs/assets/39885938/ef948f9a-5c6f-49a6-b628-8a69d6b58170)
![image](https://github.com/okis-okis/scs/assets/39885938/e2cfef78-abd4-45b2-b1f0-bfdb6b4a02fa)
Так же на мобильном телефоне, а не в симуляции девтулсе появляется горизонтальный скрол, то есть ширина больше 100

**Comment by okis-okis** [comment]
Проверь ещё раз. Если ошибка осталась, то она исправлена в новой версии вёрстки.
![1](https://github.com/okis-okis/scs/assets/67818930/67ffea49-2008-4745-bd0d-9e6e1f0dc9bb)
