### ISSUE TITLE
Форма "Свяжитесь с нами"

### ISSUE THREAD

**Issue by zendau** [okis-okis/scs#27]
1. Поле для номера телефона должно валидироваться средствами js. Обычный атрибут пропускает все ошибки
![image](https://github.com/okis-okis/scs/assets/39885938/186b9cc5-2c53-437a-abd6-3a2aeb20ba0a).
2. Нет страницы которая показывает что сообщение было успешно отправлено после клика на кнопку "Отправить". Необходимо сделать страницу с сообщением что сообщение отправлено

**Comment by okis-okis** [comment]
Встроенные средства не позволяют произвести отправку этих данных на сервер. Только после того, как данные будут изменены под определённый формат
