### ISSUE TITLE
Вывод публикаций

### ISSUE THREAD

**Issue by okis-okis** [okis-okis/scs#30]
![1](https://github.com/okis-okis/scs/assets/67818930/9b7addbb-6c8e-4d73-a3fa-da573210f423)
Если публикаций нет у работника, то список не стоит создавать

**Comment by BogdanRomanko** [comment]
согласен, исправлю

**Comment by zendau** [comment]
Я уже это делаю

**Comment by zendau** [comment]
Добавлена проверка на пустую строку.
![image](https://github.com/okis-okis/scs/assets/39885938/2849449e-3e0d-4784-85b6-9d60477c0014)
