### ISSUE TITLE
Если не указать группу у выпускника, то и выводить этот пункт не стоит

### ISSUE THREAD

**Issue by okis-okis** [okis-okis/scs#32]
Просто добавлю изображение
![1](https://github.com/okis-okis/scs/assets/67818930/fd4484ba-cc74-4d38-b527-e1f512cdc052)

**Comment by zendau** [comment]
Необходимо ли это поле вообще, может просто его убрать ? так как у выпускника уже нет группы, просто отзыв

**Comment by okis-okis** [comment]
Да, давай уберём

**Comment by zendau** [comment]
Убрал
